services:
  - type: web
    name: dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn aws1:server --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MALLOC_TRIM_THRESHOLD_
        value: 100000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: MALLOC_ARENA_MAX
        value: "2"
    autoDeploy: false
    plan: starter 